name: ðŸš€ Release

on:
  workflow_dispatch:
  push:
    branches:
      - release
    tags-ignore:
      - "*"

jobs:
  release:
    name: ðŸš€ Release Uncrash
    permissions:
      contents: write # for actions/create-release to create a release
    runs-on: ubuntu-latest
    steps:
      - name: ðŸ”§ Checkout code
        uses: actions/checkout@v6

      - name: ðŸ“¦ Get version
        run: |
          VERSION=$(grep "  VERSION" CMakeLists.txt | head -1 | awk '{print $2}')
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      #      - name: Get release text
      #        run: |
      #          export RELEASE_TEXT=$(grep -Pzo "## ${VERSION}\n(\n|.)+?\n##" CHANGELOG.md | sed '$ d')
      #          # Add multiline release text
      #          echo "RELEASE_TEXT<<EOF" >> $GITHUB_ENV
      #          echo "${RELEASE_TEXT}" >> $GITHUB_ENV
      #          echo "EOF" >> $GITHUB_ENV

      - name: ðŸ“ Extract changelog
        run: |
          awk "/^## $VERSION$/{flag=1; next} /^## [0-9]+\.[0-9]+\.[0-9]+$/{if(flag) exit} flag" CHANGELOG.md > changelog.txt

      - name: ðŸš€ Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ env.VERSION }}
          name: Release v${{ env.VERSION }}
          body_path: changelog.txt
          draft: false
          prerelease: false
